version: 2.1
jobs:
  test:
    docker:
      - image: cimg/go:1.19
    steps:
      - checkout
      - run: make test
      - run: make coverage
      - run: bash <(curl -s https://codecov.io/bash)
workflows:
  version: 2
  build:
    jobs:
      - test:
          context: org-global
