name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  promote-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Extract version from tag
        id: version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
      
      - name: Build info
        run: |
          echo "Promoting release: ${{ steps.version.outputs.VERSION }}"
          make docker-info
      
      - name: Promote Docker image
        run: |
          # The image should already exist from the main branch build
          # We're just adding the version tag to it (immutable tags - no latest)
          make docker-promote TAGS="${{ steps.version.outputs.VERSION }}"
      
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          draft: false
          prerelease: false